# Generated by Django 4.2.16 on 2025-01-31 15:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Cena',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=7)),
            ],
        ),
        migrations.CreateModel(
            name='Klient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=50)),
                ('lastname', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Sprzet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Termin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('klient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wypozyczalnia.klient')),
                ('sprzet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wypozyczalnia.sprzet')),
            ],
        ),
        migrations.CreateModel(
            name='Zamowienie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_zamowienia', models.DateField(auto_now_add=True)),
                ('cena', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wypozyczalnia.cena')),
                ('klient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wypozyczalnia.klient')),
                ('sprzet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wypozyczalnia.sprzet')),
                ('termin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wypozyczalnia.termin')),
            ],
        ),
        migrations.CreateModel(
            name='Produkt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=7)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wypozyczalnia.category')),
            ],
        ),
        migrations.AddField(
            model_name='cena',
            name='sprzet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wypozyczalnia.sprzet'),
        ),
        migrations.CreateModel(
            name='ZamowienieProdukty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=5)),
                ('price', models.DecimalField(decimal_places=2, max_digits=7)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wypozyczalnia.sprzet')),
                ('zamowienie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wypozyczalnia.zamowienie')),
            ],
            options={
                'unique_together': {('zamowienie', 'product')},
            },
        ),
    ]
